# Generated by Django 5.0.6 on 2024-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=500)),
                ('Linenous', models.CharField(max_length=20)),
                ('Language', models.CharField(max_length=200)),
                ('Style', models.CharField(max_length=200)),
            ],
        ),
    ]
