# Generated by Django 5.0.6 on 2024-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='Linenous',
            field=models.BooleanField(),
        ),
    ]
